### ISSUE TITLE
voting points template

### ISSUE THREAD

**Issue by janz93** [rughh/contriboot-rails#5]
Add a template to where to put the voting points on.
This helps a bit with the counting 

![grafik](https://user-images.githubusercontent.com/5300559/39112914-44f34680-46da-11e8-86d7-3aeb6e9a1f53.png)

ps. sorry for the bad graphic 😇

**Comment by janz93** [comment]
@halfbyte I could you assign me to the issue pls

**Comment by halfbyte** [comment]
Fixed in b0808959dbc7de6fbcd335b3233655c0a1c08972
